name: codetomobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
    
  # state managment
  bloc: ^7.2.0
  flutter_bloc: ^7.3.0

  # languages
  intl: ^0.17.0

  # env helpers
  logger: ^1.1.0

  # deal with api and models
  retrofit: ^2.0.1
  dio: ^4.0.0
  json_serializable: ^5.0.2
  json_annotation: ^4.1.0

  cupertino_icons: ^1.0.2

dependency_overrides:
  # Because every version of flutter_test from sdk depends on meta 1.3.0 and codetomobile depends on meta ^1.7.0, flutter_test from sdk is forbidden.
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^2.0.1+1
  build_runner: ^2.1.2

flutter:
  generate: true
  uses-material-design: true
