name: codetomobile
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # deal with api and models
  retrofit: any
  dio: any
  json_serializable: any
  json_annotation: any

  # local database, works on windows and macos
  sqflite_common_ffi: any
  sqlite3_flutter_libs: any
  sqflite: any

  # state managment
  bloc: ^7.2.0
  flutter_bloc: ^7.3.0

  # languages
  intl: ^0.17.0

  # util helpers
  logger: ^1.1.0
  path: ^1.8.0
  path_provider: ^2.0.1
  equatable: ^2.0.3

  # view helpers
  icon_badge: any
  photo_view: any
  cupertino_icons: ^1.0.2

dependency_overrides:
  # Because every version of flutter_test from sdk depends on meta 1.3.0 and codetomobile depends on meta ^1.7.0, flutter_test from sdk is forbidden.
  meta: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  build_runner: any

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
