enum LoadDataError {
  undefined,
}

enum RouterError {
  UNDEFINED,
  ARGS_ERROR,
}

enum LocalDatabaseError {
  OPEN_DATABASE_ERROR,
  CLOSE_DATABASE_ERROR,
  CREATE_TABLES_ERROR,
  DATABASE_PATH_NULL_ERROR,
  UNDEFINED,
  GET_FROM_DATABASE_CAST_ERROR,
  DELETE_ERROR
}
